### PR TITLE
Switch from metlinelite to Grante V3 model for failing tests

### PR DESCRIPTION
**Pull request by deewhyweb**

### CODE REVIEW

**Comment by danieloh30** [comment]
@deewhyweb Can you update the model name as same as "granite-3.0-8b-instruct" in HF?

**Comment by deewhyweb** [comment]
Is that what the model will be called when deployed to OpenShift AI?

**Comment by danieloh30** [comment]
> Is that what the model will be called when deployed to OpenShift AI?

this is a guide how we need to sync the model name and path via RHDP team :) RHOAI let us do anything we want

**Comment by deewhyweb** [comment]
Done!

**Pull request merged**
